@WebHooks = https://localhost:7116

###

POST {{WebHooks}}/orders
Content-Type: application/json

{
  "customerName": "test",
  "amount": 10000
}

###

POST {{WebHooks}}/webhooks/subscriptions
Content-Type: application/json

{
  "EventType": "OrderCreated",
  "webHookUrl": "https://webhook.site/9c157c99-186f-4946-a1de-5b87ac3de47e  ",
}

###

GET {{WebHooks}}/orders
Content-Type: application/json